# Generated by Django 4.0 on 2022-01-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(height_field='image_height', upload_to='', width_field='image_width')),
                ('title', models.CharField(max_length=200)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
