# Generated by Django 4.0 on 2022-01-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousevent',
            name='event_type',
            field=models.CharField(choices=[('EVENTS', 'Previous Events'), ('DIALOGUES', 'Dialogues'), ('WEBSITES', 'Previous Websites'), ('BLOG', 'Blog')], default='Type', max_length=20),
        ),
        migrations.AlterField(
            model_name='previousevent',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
