# Generated by Django 4.0 on 2022-01-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_previousevent_event_type_alter_previousevent_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreviousEvent',
            new_name='Action',
        ),
    ]
