# Generated by Django 4.0.1 on 2022-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='subtext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
